import { Option } from './option';

export const OPTIONS: Option[] = [
  { idOption: 1, idStep: 1, idObra: 11, name: 'Wood 1' , img_src:'../assets/images/options/Ergo2-front1(1).jpg', price: 1050.6},
  { idOption: 2, idStep: 1, idObra: 11, name: 'Wood 2' , img_src:'../assets/images/options/Ergo-front2.jpg', price: 1300},
  { idOption: 3, idStep: 1, idObra: 11, name: 'Tile 1' , img_src:'../assets/images/options/Ergo-front3.jpg', price: 1030},
  { idOption: 4, idStep: 1, idObra: 11, name: 'Tile 2' , img_src:'../assets/images/options/Ergo-front4.jpg', price: 1200.55},
  { idOption: 1, idStep: 2, idObra: 11, name: 'Paint 1' , img_src:'../assets/images/options/Ergo2-front1(1).jpg', price: 200},
  { idOption: 2, idStep: 2, idObra: 11, name: 'Paint 2' , img_src:'../assets/images/options/Ergo2-front2.jpg', price: 200},
  { idOption: 3, idStep: 2, idObra: 11, name: 'Paint 3' , img_src:'../assets/images/options/Ergo2-front3.jpg', price: 200},
  { idOption: 4, idStep: 2, idObra: 11, name: 'Paint 4' , img_src:'../assets/images/options/Ergo2-front4.jpg', price: 200},
  { idOption: 1, idStep: 3, idObra: 11, name: 'Paint 1' , img_src:'../assets/images/options/Full2-Front1(1).jpg', price: 500},
  { idOption: 2, idStep: 3, idObra: 11, name: 'Paint 2' , img_src:'../assets/images/options/Full2-Front2.jpg', price: 500},
  { idOption: 3, idStep: 3, idObra: 11, name: 'Paint 3' , img_src:'../assets/images/options/Full2-Front3.jpg', price: 500},
  { idOption: 4, idStep: 3, idObra: 11, name: 'Paint 4' , img_src:'../assets/images/options/Full2-Front4.jpg', price: 500},
  { idOption: 1, idStep: 5, idObra: 11, name: 'Option 1' , img_src:'../assets/images/options/Full-Front1(1).jpg', price: 500},
  { idOption: 2, idStep: 5, idObra: 11, name: 'Option 2' , img_src:'../assets/images/options/Full-Front2.jpg', price: 500},
  { idOption: 3, idStep: 5, idObra: 11, name: 'Option 3' , img_src:'../assets/images/options/Full-Front3.jpg', price: 500},
  { idOption: 4, idStep: 5, idObra: 11, name: 'Option 4' , img_src:'../assets/images/options/Full-Front4.jpg', price: 500},
  { idOption: 1, idStep: 1, idObra: 12, name: 'Option 1' , img_src:'../assets/images/options/Full-Front1(1).jpg', price: 500},
  { idOption: 2, idStep: 1, idObra: 12, name: 'Option 2' , img_src:'../assets/images/options/Full-Front2.jpg', price: 500},
  { idOption: 3, idStep: 1, idObra: 12, name: 'Option 3' , img_src:'../assets/images/options/Full-Front3.jpg', price: 500},
  { idOption: 4, idStep: 1, idObra: 12, name: 'Option 4' , img_src:'../assets/images/options/Full-Front4.jpg', price: 500},
  { idOption: 1, idStep: 2, idObra: 12, name: 'Option 1' , img_src:'../assets/images/options/Full-Front1.jpg', price: 500},
  { idOption: 2, idStep: 2, idObra: 12, name: 'Option 2' , img_src:'../assets/images/options/Full-Front2.jpg', price: 500},
  { idOption: 1, idStep: 4, idObra: 11, name: 'Option 1' , img_src:'../assets/images/A(1).jpg', price: 500},
];